---
abstract: 'A convenient class for text classification'
author:
  - 'Zbigniew Lukasiak <zlukasiak@opera.com>, Tadeusz Sośnierz <tsosnierz@opera.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-Classifier
no_index:
  directory:
    - t/lib
    - examples
requires:
  AI::NaiveBayes: 0.01
  AI::NaiveBayes::Learner: 0
  Carp: 0
  File::Find::Rule: 0.32
  File::Spec: 0
  List::Util: 0
  Module::Load: 0
  Moose: 1.15
  MooseX::Storage: 0.25
  Text::WordCounter: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/operasoftware/AI-Classifier
version: 0.02
